Hijack pods
ss220-space/NebulaHestia pull request #14
Opened 2021-12-25 21:53 UTC by keIgaras

# Описание

* Угон эвакуационных подов
* Рестарт в конце раунда, даже если есть тикеты
* Правка зоны

## Основные изменения

* Появилась возможность угонять эвакуационные поды, путём их взлома емагом
* Появилась возможность чинить эвакуационные поды, после их взлома емагом
* Расширена зона техов на 1 палубе
* Теперь активные тикеты не препятствуют рестарту сервера

:cl:
bugfix: 
Теперь активные тикеты не препятствуют рестарту сервера.
Раньше это мешало рестартнуться серверу, даже если тикеты впоследствии были закрыты

tweak:
Добавлена возможность угонять поды с помощью емага, для этого вам необходимо взломать емагом контроллер пода, и подождать 3 минуты до того как под "подготовится", если вы вломитесь в под раньше этого срока, вам всё равно придётся дождаться окончания таймера.

Во время взлома, идёт оповещение в канал охраны, в котором говорится местоположение пода, который вы начали взламывать.
Так же оповещение в общий канал идёт, когда вы уже улетели, в нём предупреждают об опасности разгерметизации.

У инженеров с прокаченным навыком электроники, а именно начиная с уровня trained, есть возможность с помощью гаечного ключа починить взломанный под.

mapping:
Поправил зону технических тоннелей на 1 палубе
/:cl:

2021-12-26 04:42 UTC, Vallat requested changes

2021-12-26 04:42 UTC, Vallat commented on mods/content/ss220_content/hijack_pods.dm
> +	if(istype(airlock_program) && airlock_program.memory["processing"])
```suggestion
	else if(istype(airlock_program) && airlock_program.memory["processing"])
```

2021-12-26 04:42 UTC, Vallat commented on mods/content/ss220_content/hijack_pods.dm
> +	data = list(
```suggestion
	var/datum/computer/file/embedded_program/docking/simple/docking_program = program

	var/list/data = list(
```

2021-12-26 04:42 UTC, Vallat commented on mods/content/ss220_content/hijack_pods.dm
> +	for(var/obj/machinery/door/blast/regular/escape_pod/ES in world)
Срочно переделывать ХОТЯ БЫ под список машинерии, а лучше отдельный для дверей. Какой еще in world??????

2021-12-26 04:42 UTC, Vallat commented on mods/content/ss220_content/hijack_pods.dm
> +				return
```suggestion
			if(!do_after(user, 100, src))
				return
			emagged = FALSE
			state("<font size='3'>Сброс до заводских настроек завершен!</font>")
			sleep(5)
			state("<font size='3'>Поиск центрального контроллера...</font>")
			sleep(10)
			state("<font size='3'>Найдено!")
			sleep(10)
			state("<font size='3'>Первичная настройка капсулы...</font>")
			sleep(20)
			state("<font size='3'>Успешно!</font>")
			if (istype(program, /datum/computer/file/embedded_program/docking/simple/escape_pod_berth))
				var/datum/computer/file/embedded_program/docking/simple/escape_pod_berth/arming_program = program
				for(var/datum/shuttle/autodock/ferry/escape_pod/pod in escape_pods)
					if(pod.arming_controller == arming_program)
						pod.toggle_bds(TRUE)
						break
				if (arming_program.armed || arming_program.arming)
					arming_program.unarm()

```

2021-12-26 04:42 UTC, Vallat commented on mods/content/ss220_content/hijack_pods.dm
> +		toggleDoor(memory["door_status"], tag_door, TRUE, "open")
```suggestion
	if(armed)
		return
	armed = 1
	arming = FALSE
	toggleDoor(memory["door_status"], tag_door, TRUE, "open")
```

2021-12-28 01:28 UTC, keIgaras commented on mods/content/ss220_content/hijack_pods.dm
> +	for(var/obj/machinery/door/blast/regular/escape_pod/ES in world)
Теперь используется список машинерии, только не кричи

2021-12-28 03:49 UTC, Vallat approved these changes

2021-12-28 07:54 UTC, Gaxeer requested changes

2021-12-28 07:54 UTC, Gaxeer commented on mods/content/ss220_content/hijack_pods.dm
> +#define EVAC_CHAIR(varName) var/obj/structure/bed/chair/shuttle/##varName
```suggestion
```

Мы же уже никак это не используем

2021-12-28 07:54 UTC, Gaxeer commented on mods/content/ss220_content/hijack_pods.dm
> +#undef EVAC_CHAIR
```suggestion
```

и соответственно это

2021-12-28 07:58 UTC, Gaxeer approved these changes

2021-12-29 14:30 UTC, merged