Fix FTL and balance correction. power from 0.005 to 0.001 and less cores
ss220-space/NebulaHestia pull request #64
Opened 2021-12-27 14:44 UTC by Astolaf

## Описание
Багфикс FTL и правки баланса

## Why and what will this PR improve

## Changelog

:cl:
bugfix:
1. Исправление обновления иконки порта для топлива FTL. Внутри порта все еще отображался fuel core, когда его вытаскивали.
2. Исправлена проверка времени Cooldown после прыжка. Теперь можно прыгать несколько раз. 

tweak:
1. Макс дальность прыжка теперь 14  клеток.  было 8 
        moderate_jump_distance = 8.  было 6
	safe_jump_distance = 4. было 3 
2. Топлива теперь нужно примерно в 2 раза меньше. 
3. Множитель необходимой энергии с 0.005 на 0.001

:cl:

2021-12-27 18:02 UTC, Astolaf commented
Сжделаю правки для скопления If. Плюс выпал runtime

[runtime.txt](https://github.com/ss220-space/NebulaHestia/files/7781256/runtime.txt)

2021-12-30 01:31 UTC, Astolaf commented
Должен был все исправить. Плюс новый индикатор заряда в консоли. Можно сливать

2021-12-30 13:01 UTC, Vallat requested changes

2021-12-30 13:01 UTC, Vallat commented on code/modules/overmap/ftl_shunt/computer.dm
> +		core_ftl = 1
```suggestion
	var/core_ftl  = max(1, round(recalc_cost() / 2)) //cores to jump
```

2021-12-30 13:01 UTC, Vallat commented on code/modules/overmap/ftl_shunt/core.dm
> +	var/cooldown_timer
Неиспользованная нигде переменная

2021-12-30 13:01 UTC, Vallat commented on code/modules/overmap/ftl_shunt/core.dm
> +			required_jump_cores = 1
```suggestion
		required_jump_cores = max(1, round(shunt_distance / 2))
```

2021-12-30 15:25 UTC, Astolaf commented
Исправил замечания  по коду. Это финал

2022-01-03 19:42 UTC, merged