Captain? More like, Commandor
ss220-space/NebulaHestia pull request #72
Opened 2021-12-27 19:00 UTC by keIgaras

## Description of changes

## Why and what will this PR improve

## Authorship

## Changelog

:cl:
prefix:
/:cl:

2021-12-28 00:50 UTC, Gaxeer requested changes

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +		for(var/mob/M in global.player_list)
```suggestion
		for(var/mob/M as anything in global.player_list)
```

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +			if(M.client && M.mind && M.mind.assigned_job && (M.mind.assigned_job.title in required_role))
```suggestion
			if(M.mind?.assigned_job && (M.mind?.assigned_job.title in required_role))
```
в списке player_list присутствуют мобы ТОЛЬКО с подлюченным клиентом. Касательно присутствия MIND в мобе не уверен, но вот то что это можно заменять на null safe ?. - считаю будет правильно.

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +	for(var/datum/job/J in SSjobs.primary_job_datums)
```suggestion
	for(var/datum/job/J as anything in SSjobs.primary_job_datums)
```

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +		for(var/mob/player in global.player_list)
```suggestion
		for(var/mob/player as anything in global.player_list)
```

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +			if(player.client && player.mind && player.mind.assigned_job && (player.mind.assigned_job.title in required_role))
```suggestion
			if(player.mind?.assigned_job && (player.mind?.assigned_job.title in required_role))
```

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +	for(var/datum/job/primary_job in SSjobs.primary_job_datums)
```suggestion
	for(var/datum/job/primary_job as anything in SSjobs.primary_job_datums)
```

2021-12-28 00:50 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +				return 1
```suggestion
		if(!(primary_job.title in required_role))
			return
			
		if(primary_job.current_positions || !primary_job.total_positions)
			return 1
```

2021-12-28 08:07 UTC, Gaxeer requested changes

2021-12-28 08:07 UTC, Gaxeer commented on code/game/jobs/job/_job.dm
> +			if(player.mind?.assigned_job && (player.mind?.assigned_job.title in required_role))
```suggestion
			if(player.mind?.assigned_job?.title in required_role)
```

2021-12-28 08:07 UTC, Gaxeer commented on code/modules/admin/verbs/randomverbs.dm
> +/client/proc/cmd_offer_to_ghosts_to_be_somebody(mob/living/selected_mob as mob in SSmobs.mob_list)
```suggestion
/client/proc/cmd_offer_to_ghosts_to_be_somebody(mob/living/selected_mob as anything in living_mob_list_)
```

2021-12-28 08:07 UTC, Gaxeer commented on code/modules/admin/verbs/randomverbs.dm
> +		return
```suggestion
```
По идее это не будет нужно. Проверь у себя на локалке

2021-12-30 13:10 UTC, Vallat approved these changes

2021-12-30 13:10 UTC, Vallat commented on code/modules/admin/verbs/randomverbs.dm
> +							selected_mob.ckey = player_ghost.ckey
```suggestion
	if(alert("Вы уверены?", "Confirm", "Да", "Нет") == "Нет")
		return
	for(var/mob/observer/ghost/player_ghost in global.player_list)
		spawn() if(alert(player_ghost, "Вам предложили вселиться в [selected_mob], вы согласны?", "Offer", "Да", "Нет") == "Да")
				if(selected_mob?.check_have_client())
					alert(player_ghost, "Извините, но вы опоздали, кто-то ответил на запрос быстрее вас.")
				else if(selected_mob)
					selected_mob.ckey = player_ghost.ckey
```

2021-12-31 18:11 UTC, keIgaras commented
Немного отредактирую фиксы под фиксы офов, и если не будет вопросов можно мерджить

2021-12-31 22:53 UTC, keIgaras commented
:+1:

2022-01-03 19:43 UTC, merged